---
argument_specs:
  main:
    short_description: Install packages from the AUR using makepkg
    description:
      - Install packages from the Arch User Repository using makepkg
    author:
      - Daniel Lowry (github.com/dandyrow)
    options:
      aur_package:
        description:
          - List of package names to install from the AUR
        type: list
        elements: str
        required: true

      non_root_aur_user:
        description:
          - Non-root user which is used to run makepkg.
          - >-
            Makepkg can't be run as root see
            https://wiki.archlinux.org/title/Makepkg for information why.
          - >-
            This user must be able to run pacman as root without a password
            for this role to work.
        type: str
        default: aur_builder

      makepkg_build_dependencies:
        description:
          - List of packages that makepkg depends on.
          - Role will install them if not already installed.
          - User of this role shouldn't need to change this variable.
          - Documented only for completeness.
        type: list
        elements: str
        default: ['git', 'make', 'binutils', 'fakeroot']
